import 'package:flutter_test/flutter_test.dart';
import 'package:esc_pos_utils/esc_pos_utils.dart';
import 'package:visionpos/services/receipt_builder.dart';

void main() {
  group('ReceiptBuilder Tests', () {
    late ReceiptBuilder rb;

    setUpAll(() async {
      // Create ReceiptBuilder without font for basic testing
      rb = await ReceiptBuilder.create(
        paper: PaperSize.mm80,
        debug: true,
        useRasterFallback: false,
      );
    });

    test('buildCustomer generates bytes for basic order', () async {
      final order = {
        'orderNumber': '123',
        'paymentMethod': 'Cash',
        'subtotal': 10.0,
        'tax': 1.0,
        'total': 11.0,
      };
      final items = [
        {'name': 'شاورما', 'quantity': 2, 'unitPrice': 5.0},
      ];

      final bytes = await rb.buildCustomer(order, items: items);
      expect(bytes, isNotEmpty);
      expect(bytes.length, greaterThan(100)); // Basic check for content
    });

    test('buildKitchen generates bytes for basic order', () async {
      final order = {'orderNumber': '456'};
      final items = [
        {'name': 'بيتزا', 'quantity': 1, 'notes': 'بدون جبن'},
      ];

      final bytes =
          await rb.buildKitchen(order, kitchenName: 'مطبخ', items: items);
      expect(bytes, isNotEmpty);
      expect(bytes.length, greaterThan(50));
    });

    test('buildCustomer with empty items computes subtotal', () async {
      final order = {'orderNumber': '789'};
      final items = [
        {'name': 'عصير', 'quantity': 3, 'unitPrice': 2.0},
      ];

      final bytes = await rb.buildCustomer(order, items: items);
      expect(bytes, isNotEmpty);
      // Subtotal should be computed as 6.0
    });

    test('Arabic digit conversion works', () async {
      final rbWithDigits = await ReceiptBuilder.create(
        paper: PaperSize.mm80,
        debug: true,
        useArabicIndicDigits: true,
      );

      final order = {'orderNumber': '123'};
      final items = [
        {'name': 'صنف', 'quantity': 1, 'unitPrice': 1.0}
      ];

      final bytes = await rbWithDigits.buildCustomer(order, items: items);
      expect(bytes, isNotEmpty);
      // Note: Actual digit conversion would need inspection of generated bytes
    });

    test('buildCustomer with tips and tax', () async {
      final order = {
        'orderNumber': '999',
        'subtotal': 20.0,
        'tax': 2.0,
        'tips': 3.0,
        'total': 25.0,
      };
      final items = [
        {'name': 'سلطة', 'quantity': 1, 'unitPrice': 20.0}
      ];

      final bytes = await rb.buildCustomer(order, items: items);
      expect(bytes, isNotEmpty);
    });

    test('buildKitchen with multiple items', () async {
      final order = {'orderNumber': '111'};
      final items = [
        {'name': 'برجر', 'quantity': 2},
        {'name': 'بطاطس', 'quantity': 1, 'notes': 'مقلية'},
      ];

      final bytes =
          await rb.buildKitchen(order, kitchenName: 'مطبخ رئيسي', items: items);
      expect(bytes, isNotEmpty);
    });
  });
}
